name: Generate Ascii Artwork

on: push

jobs:
    generate-ascii:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: List Repo files
              run: ls -la

            - name: Execute generate-ascii script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

