name: variables-secrets-workflow

env:
  key3: value3
  key4: value4

on: push

jobs:
  variables-secrets:
    runs-on: ubuntu-latest
    env:
        key1: value1
        key2: value2
    steps:
    - name: Print Job Env Variables
      run: |
        echo Job env vars  values are $key1 and $key2
        echo Workflow env vars values are $key3 and $key4
        echo Username is ${{ vars.USERNAME }}
        echo Password is ${{ secrets.PASSWORD }}